import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/[...components]/header/Header";
import LinkedInFab from "./[...components]/linkedInFab/LinkedInFab";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-black h-screen w-screen bg-white grid grid-cols-1">
        <Header />
        <div className={"pt-20 h-full overflow-auto " + inter.className}>
          <div className="w-screen h-full flex flex-col">
            <LinkedInFab />
            <div className="w-full h-full bg-yellow-500">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
